# Generated by Django 4.2 on 2023-09-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorys',
            name='category_image',
            field=models.ImageField(default='img', upload_to='dynamicimg'),
        ),
        migrations.AddField(
            model_name='group_frame_products',
            name='product_image',
            field=models.ImageField(default='img', upload_to='dynamicimg'),
        ),
        migrations.AddField(
            model_name='singal_frame_products',
            name='product_image',
            field=models.ImageField(default='img', upload_to='dynamicimg'),
        ),
    ]
