# Generated by Django 4.2 on 2023-09-15 12:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_categorys_category_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(max_length=10)),
                ('addres', models.CharField(max_length=200)),
                ('product', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(max_length=10)),
                ('orderplacedate', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
