# Generated by Django 4.2 on 2023-09-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='totalprice',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
