# Generated by Django 4.2 on 2023-09-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='image',
            field=models.ImageField(default='img', upload_to='dynamicimg'),
        ),
    ]
